---
kind: pipeline
type: docker
name: kaniko-build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: ghcr.io/finitum/drone-kaniko:0.8.1
  settings:
    dockerfile: Dockerfile
    context: .

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

clone:
  disable: true

trigger:
  ref:
  - refs/heads/master
  - refs/heads/testing
  status:
    - success
    - failure
  event:
    exclude:
    - cron

depends_on:
- kaniko-build

steps:
  - name: discord
    pull: if-not-exists
    image: appleboy/drone-discord:latest
    settings:
      message: "{{#success build.status}} ✅ [Build #{{build.number}}]({{build.link}}) of `{{repo.name}}` succeeded.\nevent: **`{{build.event}}`**\ncommit [`${DRONE_COMMIT_SHA:0:7}`](https://git.dotya.ml/${DRONE_REPO}/commit/${DRONE_COMMIT_SHA}) by {{commit.author}} on `{{commit.branch}}`\n```{{commit.message}}``` {{else}} ❌ [Build #{{build.number}}]({{build.link}}) of `{{repo.name}}` failed.\nevent: **`${DRONE_BUILD_EVENT}`**\ncommit [`${DRONE_COMMIT_SHA:0:7}`](https://git.dotya.ml/${DRONE_REPO}/commit/${DRONE_COMMIT_SHA}) by {{commit.author}} on `{{commit.branch}}`\n```{{commit.message}}``` {{/success}}\n"
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
